Controllers/RolesController.cs
using EDalolatnoma.MVC.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EDalolatnoma.MVC.Controllers
{


[Authorize(Roles = "Администратор")]
public class RolesController : Controller
{
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        public RolesController(RoleManager<IdentityRole> roleManager, ApplicationDbContext context)
        {
            _roleManager = roleManager;
               _context = context;  
        }

    public async Task<IActionResult> Index()
    {
        var roles = await _roleManager.Roles.ToListAsync();
        return View(roles);
    }
    [HttpPost]
    public async Task<IActionResult> AddRole(string roleName)
    {
        if (roleName != null)
        {
            await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
        }
        return RedirectToAction("Index");
    }


        public async Task<IActionResult> Edit(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IdentityRole role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var roleUpdate = await _context.Roles.FindAsync(id);
                roleUpdate.Name = role.Name;

                await _roleManager.UpdateAsync(roleUpdate);

                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }
    }
}

Controllers/UsersController.cs
using EDalolatnoma.MVC.Data;
using EDalolatnoma.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EDalolatnoma.MVC.Controllers
{

[Authorize]
public class UsersController : Controller
{


    private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UsersController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
    {
        _userManager = userManager;
            _context = context; 
    }
    public async Task<IActionResult> Index()
    {
        var currentUser = await _userManager.GetUserAsync(HttpContext.User);
        var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            foreach (var item in allUsersExceptCurrentUser)
            {
                var company = _context.Company.Find(item.Company_id);
                if (company != null) item.Company = company.CompanyShortName;    
                var roles = await _userManager.GetRolesAsync(item);
                if (roles != null) item.Roles = string.Join(", ", roles);
            }

        return View(allUsersExceptCurrentUser);
    }
}
}

Controllers/WellsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EDalolatnoma.MVC.Data;
using EDalolatnoma.MVC.Models;

namespace EDalolatnoma.MVC.Controllers
{
    public class WellsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WellsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Wells
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Well.Include(w => w.Field).Include(w => w.WellStatus);
            return View(await applicationDbContext.ToListAsync());
        }



        [HttpGet]
        public JsonResult GetWells()
        {
            var fields = _context.Well
                         .Include(i => i.Field).ThenInclude(i=>i.Company)
                         .Include(i=>i.WellStatus)
                         .AsNoTracking().ToList();
            return Json(new { data = fields });
        }

        [HttpGet]
        public JsonResult GetFields(int id)
        {
            var fields = _context.Field.Where(c=>c.Company_id==id)
                         .AsNoTracking().ToList();
            return Json(new SelectList(fields, "Id", "FieldName"));
        }
        
        [DbFunction(Name = "SOUNDEX", Schema = "")]
        public static string SoundsLike(string keyword)
        {
            throw new NotImplementedException();
        }
        // GET: Wells/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var well = await _context.Well
                .Include(w => w.Field)
                .Include(w => w.WellStatus)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (well == null)
            {
                return NotFound();
            }

            return View(well);
        }

        // GET: Wells/Create
        public IActionResult Create()
        {
           
            ViewData["Company_id"] = new SelectList(_context.Company, "Id", "CompanyFullName");
            ViewData["Field_id"] = new SelectList(_context.Field,"Id", "FieldName");
            ViewData["WellStatus_id"] = new SelectList(_context.Set<WellStatus>(), "Id", "StatusName");
            return View();
        }

       

        // POST: Wells/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,WellName,Field_id,WellStatus_id")] Well well)
        {
            if (ModelState.IsValid)
            {
                _context.Add(well);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Field_id"] = new SelectList(_context.Field, "Id", "FieldName", well.Field_id);
            ViewData["WellStatus_id"] = new SelectList(_context.Set<WellStatus>(), "Id", "StatusName", well.WellStatus_id);
            return View(well);
        }

        // GET: Wells/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var well = await _context.Well.FindAsync(id);
            if (well == null)
            {
                return NotFound();
            }
            ViewData["Field_id"] = new SelectList(_context.Field, "Id", "FieldName", well.Field_id);
            ViewData["WellStatus_id"] = new SelectList(_context.Set<WellStatus>(), "Id", "StatusName", well.WellStatus_id);
            return View(well);
        }

        // POST: Wells/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WellName,Field_id,WellStatus_id")] Well well)
        {
            if (id != well.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(well);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WellExists(well.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Field_id"] = new SelectList(_context.Field, "Id", "FieldName", well.Field_id);
            ViewData["WellStatus_id"] = new SelectList(_context.Set<WellStatus>(), "Id", "StatusName", well.WellStatus_id);
            return View(well);
        }

        // GET: Wells/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var well = await _context.Well
                .Include(w => w.Field).ThenInclude(c=>c.Company)
                .Include(w => w.WellStatus)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (well == null)
            {
                return NotFound();
            }

            return View(well);
        }

        // POST: Wells/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var well = await _context.Well.FindAsync(id);
            _context.Well.Remove(well);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WellExists(int id)
        {
            return _context.Well.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using EDalolatnoma.MVC.Constants
@{
    bool kernoDb = (AuthorizationService.AuthorizeAsync(User, Permissions.KernoDb.View)).Result.Succeeded,
                 company = (AuthorizationService.AuthorizeAsync(User, Permissions.Company.View)).Result.Succeeded,
                 fields = (AuthorizationService.AuthorizeAsync(User, Permissions.Fields.View)).Result.Succeeded,
                 wells = (AuthorizationService.AuthorizeAsync(User, Permissions.Wells.View)).Result.Succeeded,
                 wellStatus = (AuthorizationService.AuthorizeAsync(User, Permissions.WellStatus.View)).Result.Succeeded,
                 usersList = User.IsInRole("Администратор"),
                 rolesList = User.IsInRole("Администратор"),
                 permissionList = (AuthorizationService.AuthorizeAsync(User, Permissions.PermissionList.View)).Result.Succeeded;
}
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>E-DALOLATNOMA</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/template/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="~/template/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css"> 
  <link rel="stylesheet" href="~/template/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" href="~/template/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="~/template/plugins/select2/css/select2.min.css"> 
  <link rel="stylesheet" href="~/template/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css"> 
  <!-- Theme style -->
  <link rel="stylesheet" href="~/template/dist/css/adminlte.min.css">
   <link rel="stylesheet" href="~/lib/zoomify/src/zoomify.css"> 
</head>

<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      
      <li class="nav-item">
         <partial name="_LoginPartial" />
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-controller="Home" asp-action="Index" class="brand-link">
      <img src="~/images/logoUNG.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">E-DALOLATNOMA</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
     
      </div>

      <!-- SidebarSearch Form -->
     
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->


          <li class="nav-item">
            <a asp-controller="Home" asp-action="Index" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
               Главная
              
              </p>
            </a>
          </li>
                        @if (kernoDb)
                        {
                           
                        }
                        <li class="nav-item">
                            <a asp-controller="Dalolatnomalar" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-database"></i>
                                <p>
                                    
                                    ДАЛОЛАТНОМА
                                </p>
                            </a>
                        </li>

               
                    <li class="nav-header">СПРАВОЧНИК</li> 
                
                      
                       
                            <li class="nav-item">
                                <a asp-controller="Companies" asp-action="Index" class="nav-link">

                                    <i class="nav-icon fas fa-city"></i>
                                    <p>Организации</p>
                                </a>
                            </li>

                      


                      @* 
                            <li class="nav-item">
                                <a asp-controller="Fields" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fas fa-globe-asia"></i>
                                    <p>Месторождение</p>
                                </a>
                            </li> *@
                       

                       
                           @*  <li class="nav-item">
                                <a asp-controller="Wells" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fab fa-gripfire"></i>
                                    <p>Скважины</p>
                                </a>
                            </li>
 *@


                        
@*                             <li class="nav-item">
                                <a asp-controller="WellStatus" asp-action="Index" class="nav-link">

                                    <i class="nav-icon far fa-lightbulb"></i>
                                    <p>Статусы скважины</p>
                                </a>
                            </li> *@
                      

                        @if (usersList||rolesList)
                        {   }

                        <li class="nav-header">АДМИНИСТРИРОВАНИЯ</li>

                        @if (usersList)
                        {

                           
                        }
                        <li class="nav-item">
                            <a asp-controller="Users" asp-action="Index" class="nav-link">

                                <i class="nav-icon fas fa-users"></i>
                                <p>Пользователи</p>
                            </a>
                        </li>
                        @if (rolesList)
                        {

                          

                        }
                        <li class="nav-item">
                            <a asp-controller="Roles" asp-action="Index" class="nav-link">

                                <i class="nav-icon fas fa-user-tag"></i>
                                <p>Роли</p>
                            </a>
                        </li>

         
         
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
             
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

     @RenderBody()

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <footer class="main-footer">
    <strong>&copy @DateTime.Now.Year <a href="https://ung.uz">UZBEKNEFTEGAZ</a>.</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Версия</b> 2.1
    </div>
  </footer>
  <!-- /.control-sidebar -->
</div>
<script src="~/template/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/template/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables  & Plugins -->
<script src="~/template/plugins/select2/js/select2.full.min.js"></script>
<script src="~/template/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/template/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/template/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/template/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/template/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/template/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/template/plugins/jszip/jszip.min.js"></script>
<script src="~/template/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/template/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/template/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/template/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/template/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<!-- AdminLTE App -->
<script src="~/template/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/template/dist/js/demo.js"></script>
<script src="~/template/plugins/moment/moment.min.js"></script>
<script src="~/template/plugins/moment/locale/ru.js"></script>
<script src="~/lib/zoomify/src/zoomify.min.js"></script>

<!-- Page specific script -->
<script src="~/js/site.js" asp-append-version="true"></script>

@await Component.InvokeAsync("Notyf") 
@await RenderSectionAsync("Scripts", required: false)

</body>
</html>